name: Publish to NPM

on:
  push:
    branches: [master]

jobs:
  bump_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check last commit for version message
        shell: bash
        run: |
          versionPattern=^[0-9]+\.[0-9]+\.[0-9]+$
          msg="$(git log -1 --pretty=%B)"

          if [[ ! $msg =~ $versionPattern ]]; then
            exit 1
          fi
          exit 0
      - name: update patch version
        if: failure()
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    needs:
      - bump_version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: npm test
      - run: npm run build
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_ACCESS_TOKEN }}
